using Stockapp.Data.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stockapp.Data.Entities
{
    public class Actions : ISoftDelete, Identificable
    {
        /// <summary>
        /// Id Generated by database
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Reference to the portfolio
        /// </summary>
        public long PortfolioId { get; set; }

        /// <summary>
        /// Portfolio owner of the Actions
        /// </summary>
        public virtual Portfolio Portfolio { get; set; }

        /// <summary>
        /// Reference to the Stock
        /// </summary>
        public long StockId { get; set; }

        /// <summary>
        /// Actions are from this stock
        /// </summary>
        public Stock Stock { get; set; }

        /// <summary>
        /// Number of actions owned
        /// </summary>
        public double QuantityOfActions { get; set; }

        /// <summary>
        /// Soft delete
        /// </summary>
        public bool IsDeleted { get; set; }
    }
}
